#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}/" /etc/nginx/sites-available/default

service nginx restart
