#!/usr/bin/env bash
# shellcheck disable SC2154 
#Configures Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo  "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a\        rewrite ^/redirect_me https://www.github.com/ThePaapyK permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/404_page.html
sudo sed -i '25i\        error_page 404 /404_page.html;' /etc/nginx/sites-available/default
sudo sed -i "26i\        add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default 
sudo service nginx reload
sudo service nginx restart
