#!/usr/bin/env bash
# Install the load balanecer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo 'ENABLED=1' >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << CONFIG
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 38555-web-01 54.157.191.136:80 check
    server 38555-web-02 54.157.163.118:80 check
CONFIG
sudo service haproxy restart
